### ISSUE TITLE
using hashed empty string for payload except for S3.

### ISSUE THREAD

**Issue by kenta-aktsk** [bryanjos/aws_auth#17] opened 2016-05-17 09:41 UTC
Hi, in `AWSAuth.QueryParameters.sign/8` function, `AWSAuth.Utils.build_canonical_request/5` function is called with `:unsigned` payload parameter.

So `hashed_payload` variable in `AWSAuth.Utils.build_canonical_request/5` function is set to `"UNSIGNED-PAYLOAD"`.

But, I think `"UNSIGNED-PAYLOAD"` is only for S3.
[S3: Authenticating Requests: Using Query Parameters](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html)

[In this guide](http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html), they instruct to use hashed empty string if payload is empty.

> If the payload is empty, use an empty string as the input to the hash function. 
> Example hashed payload (empty string)
> e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

I'm not sure my report is right or wrong, but when I use `AWSAuth.QueryParameters.sign/8` function to call AWS Elasticsearch service, `The request signature we calculated does not match the signature you provided` error message returned.

But when I modify your code in `AWSAuth.QueryParameters.sign/8` function like below, worked fine.

``` elixir
string_to_sign = AWSAuth.Utils.build_canonical_request(http_method, uri.path, params, headers, AWSAuth.Utils.hash_sha256(""))
```

**Comment by bryanjos** [comment] 2016-05-17 14:17
Going to close this as it looks like a duplicate of #16. I will try to update it when I get some free time or accept any PRs that resolve it

**Closed as completed by bryanjos** 2016-05-17 14:17 UTC
